/**
 * @file customer.h
 */
#ifndef CUSTOMER_H
#define CUSTOMER_H

/*******************************************************************************
 * Includes
 ******************************************************************************/
#include "entity_base.h"
#include <vector>
#include <string>
#include "vector3d.h"
#include "vector2d.h"

namespace csci3081 {

/*******************************************************************************
 * Class Definitions
 ******************************************************************************/
/**
 * @brief Customer class for holding information about the customer. Only holds customer
 * destination for now.
 *
 */
class Customer : public csci3081::EntityBase {
    public:
        /**
        * Constructor: Initializes the customer object with details specified by val
        * Customers are generated by the customer factory class.
        */
        Customer(const picojson::object& val);

        /**
        * Returns a Vector3D object specifying the customer's location.
        */
        Vector3D getDest() const;

    private:
        Vector3D dest;

};

}  // namespace csci3081


#endif  // CUSTOMER_H
